import { categories } from "./categories";

// 📋 Products Data (48 Products Total)
export const products = [
  // ═══════════════════════════════════════
  // PERFUMES (12 products)
  // Men: 3, Women: 3, Unisex: 3, Oud: 3
  // ═══════════════════════════════════════
  // MEN (3)
  {
    id: 1,
    slug: "mens-oud-royal",
    name: "Men's Oud Royal",
    price: 5500,
    compareAtPrice: 7000,
    image: "https://images.unsplash.com/photo-1594035910387-fea47794261f?w=400&h=400&fit=crop",
    rating: 4.8,
    reviewCount: 120,
    badge: "Best Seller",
    category: "perfumes",
    subcategory: "Men",
    inStock: true,
    description: "Bold masculine fragrance with oud and leather notes.",
  },
  {
    id: 2,
    slug: "mens-tobacco-vanilla",
    name: "Men's Tobacco Vanilla",
    price: 4800,
    compareAtPrice: null,
    image: "https://images.unsplash.com/photo-1615634260167-c8cdede054de?w=400&h=400&fit=crop",
    rating: 4.7,
    reviewCount: 85,
    badge: null,
    category: "perfumes",
    subcategory: "Men",
    inStock: true,
    description: "Warm tobacco and vanilla blend for the modern man.",
  },
  {
    id: 3,
    slug: "mens-black-intense",
    name: "Men's Black Intense",
    price: 6200,
    compareAtPrice: 7500,
    image: "https://images.unsplash.com/photo-1523293182086-7651a899d37f?w=400&h=400&fit=crop",
    rating: 4.9,
    reviewCount: 140,
    badge: "Sale",
    category: "perfumes",
    subcategory: "Men",
    inStock: true,
    description: "Intense woody fragrance for evening wear.",
  },

  // WOMEN (3)
  {
    id: 4,
    slug: "womens-rose-elegance",
    name: "Women's Rose Elegance",
    price: 4500,
    compareAtPrice: 5500,
    image: "https://images.unsplash.com/photo-1541643600914-78b084683601?w=400&h=400&fit=crop",
    rating: 4.8,
    reviewCount: 200,
    badge: "Best Seller",
    category: "perfumes",
    subcategory: "Women",
    inStock: true,
    description: "Elegant rose fragrance for the sophisticated woman.",
  },
  {
    id: 5,
    slug: "womens-jasmine-dream",
    name: "Women's Jasmine Dream",
    price: 4200,
    compareAtPrice: null,
    image: "https://images.unsplash.com/photo-1592945403244-b3fbafd7f539?w=400&h=400&fit=crop",
    rating: 4.7,
    reviewCount: 150,
    badge: null,
    category: "perfumes",
    subcategory: "Women",
    inStock: true,
    description: "Soft jasmine fragrance for everyday elegance.",
  },
  {
    id: 6,
    slug: "womens-cherry-bloom",
    name: "Women's Cherry Bloom",
    price: 4100,
    compareAtPrice: null,
    image: "https://images.unsplash.com/photo-1595425970377-c9703cf48b6d?w=400&h=400&fit=crop",
    rating: 4.6,
    reviewCount: 110,
    badge: "New",
    category: "perfumes",
    subcategory: "Women",
    inStock: true,
    description: "Fruity cherry blossom scent for the modern woman.",
  },

  // UNISEX (3)
  {
    id: 7,
    slug: "unisex-musk-white",
    name: "Unisex Musk White",
    price: 4800,
    compareAtPrice: 5500,
    image: "https://images.unsplash.com/photo-1587017539504-67cfbddac569?w=400&h=400&fit=crop",
    rating: 4.7,
    reviewCount: 90,
    badge: "New",
    category: "perfumes",
    subcategory: "Unisex",
    inStock: true,
    description: "Clean musk fragrance suitable for everyone.",
  },
  {
    id: 8,
    slug: "unisex-amber-wood",
    name: "Unisex Amber Wood",
    price: 5200,
    compareAtPrice: null,
    image: "https://images.unsplash.com/photo-1616949755610-8c9bbc08f138?w=400&h=400&fit=crop",
    rating: 4.8,
    reviewCount: 75,
    badge: null,
    category: "perfumes",
    subcategory: "Unisex",
    inStock: true,
    description: "Warm amber and wood fragrance for all genders.",
  },
  {
    id: 9,
    slug: "unisex-citrus-fresh",
    name: "Unisex Citrus Fresh",
    price: 3600,
    compareAtPrice: 4200,
    image: "https://images.unsplash.com/photo-1595425959632-34f2822322ce?w=400&h=400&fit=crop",
    rating: 4.6,
    reviewCount: 100,
    badge: "Sale",
    category: "perfumes",
    subcategory: "Unisex",
    inStock: true,
    description: "Refreshing citrus fragrance for daily use.",
  },

  // OUD (3)
  {
    id: 10,
    slug: "oud-arabian-nights",
    name: "Oud Arabian Nights",
    price: 8500,
    compareAtPrice: 10000,
    image: "https://images.unsplash.com/photo-1594035910387-fea47794261f?w=400&h=400&fit=crop",
    rating: 4.9,
    reviewCount: 250,
    badge: "Best Seller",
    category: "perfumes",
    subcategory: "Oud",
    inStock: true,
    description: "Premium Arabian oud fragrance for special occasions.",
  },
  {
    id: 11,
    slug: "oud-royal-gold",
    name: "Oud Royal Gold",
    price: 9500,
    compareAtPrice: 12000,
    image: "https://images.unsplash.com/photo-1594035910387-fea47794261f?w=400&h=400&fit=crop",
    rating: 5.0,
    reviewCount: 85,
    badge: null,
    category: "perfumes",
    subcategory: "Oud",
    inStock: true,
    description: "Luxurious oud fragrance for connoisseurs.",
  },
  {
    id: 12,
    slug: "oud-musk-blend",
    name: "Oud & Musk Blend",
    price: 6800,
    compareAtPrice: null,
    image: "https://images.unsplash.com/photo-1615634260167-c8cdede054de?w=400&h=400&fit=crop",
    rating: 4.7,
    reviewCount: 60,
    badge: "New",
    category: "perfumes",
    subcategory: "Oud",
    inStock: true,
    description: "Unique oud and musk blend for a lasting impression.",
  },

  // ═══════════════════════════════════════
  // JEWELRY (12 products)
  // Rings: 3, Necklaces: 3, Earrings: 3, Bracelets: 3
  // ═══════════════════════════════════════
  // RINGS (3)
  {
    id: 13,
    slug: "diamond-solitaire-ring",
    name: "Diamond Solitaire Ring",
    price: 15000,
    compareAtPrice: 18000,
    image: "https://images.unsplash.com/photo-1605100804763-247f67b3557e?w=400&h=400&fit=crop",
    rating: 5.0,
    reviewCount: 30,
    badge: "Best Seller",
    category: "jewelry",
    subcategory: "Rings",
    inStock: true,
    description: "Stunning diamond solitaire ring in white gold.",
  },
  {
    id: 14,
    slug: "gold-band-ring",
    name: "Gold Band Ring",
    price: 5500,
    compareAtPrice: null,
    image: "https://images.unsplash.com/photo-1611591437281-460bfbe1220a?w=400&h=400&fit=crop",
    rating: 4.7,
    reviewCount: 85,
    badge: null,
    category: "jewelry",
    subcategory: "Rings",
    inStock: true,
    description: "Classic gold band ring for daily wear.",
  },
  {
    id: 15,
    slug: "rose-gold-engagement-ring",
    name: "Rose Gold Engagement Ring",
    price: 12000,
    compareAtPrice: 14500,
    image: "https://images.unsplash.com/photo-1599643477877-530eb83abc8e?w=400&h=400&fit=crop",
    rating: 4.9,
    reviewCount: 55,
    badge: "Sale",
    category: "jewelry",
    subcategory: "Rings",
    inStock: true,
    description: "Beautiful rose gold ring with diamond accent.",
  },

  // NECKLACES (3)
  {
    id: 16,
    slug: "gold-plated-necklace-set",
    name: "Gold Plated Necklace Set",
    price: 3200,
    compareAtPrice: null,
    image: "https://images.unsplash.com/photo-1515562141207-7a88fb7ce338?w=400&h=400&fit=crop",
    rating: 4.9,
    reviewCount: 200,
    badge: "New",
    category: "jewelry",
    subcategory: "Necklaces",
    inStock: true,
    description: "Elegant 22K gold plated necklace set.",
  },
  {
    id: 17,
    slug: "pearl-pendant-necklace",
    name: "Pearl Pendant Necklace",
    price: 2600,
    compareAtPrice: 3400,
    image: "https://images.unsplash.com/photo-1599643478518-a784e5dc4c8f?w=400&h=400&fit=crop",
    rating: 4.9,
    reviewCount: 30,
    badge: "Best Seller",
    category: "jewelry",
    subcategory: "Necklaces",
    inStock: true,
    description: "Elegant pearl pendant necklace.",
  },
  {
    id: 18,
    slug: "diamond-pendant-necklace",
    name: "Diamond Pendant Necklace",
    price: 8800,
    compareAtPrice: 10500,
    image: "https://images.unsplash.com/photo-1611652022419-a9419f74343d?w=400&h=400&fit=crop",
    rating: 4.8,
    reviewCount: 60,
    badge: "Sale",
    category: "jewelry",
    subcategory: "Necklaces",
    inStock: true,
    description: "Beautiful diamond pendant on gold chain.",
  },

  // EARRINGS (3)
  {
    id: 19,
    slug: "rose-gold-earrings",
    name: "Rose Gold Earrings",
    price: 1800,
    compareAtPrice: null,
    image: "https://images.unsplash.com/photo-1535632066927-ab7c9ab60908?w=400&h=400&fit=crop",
    rating: 4.6,
    reviewCount: 75,
    badge: "New",
    category: "jewelry",
    subcategory: "Earrings",
    inStock: true,
    description: "Delicate rose gold earrings for daily wear.",
  },
  {
    id: 20,
    slug: "diamond-stud-earrings",
    name: "Diamond Stud Earrings",
    price: 4200,
    compareAtPrice: null,
    image: "https://images.unsplash.com/photo-1631982690223-8aa4be0a2497?w=400&h=400&fit=crop",
    rating: 4.7,
    reviewCount: 45,
    badge: null,
    category: "jewelry",
    subcategory: "Earrings",
    inStock: true,
    description: "Classic diamond stud earrings.",
  },
  {
    id: 21,
    slug: "pearl-drop-earrings",
    name: "Pearl Drop Earrings",
    price: 2800,
    compareAtPrice: 3500,
    image: "https://images.unsplash.com/photo-1635767798638-3e25273a8236?w=400&h=400&fit=crop",
    rating: 4.8,
    reviewCount: 60,
    badge: "Sale",
    category: "jewelry",
    subcategory: "Earrings",
    inStock: true,
    description: "Elegant pearl drop earrings.",
  },

  // BRACELETS (3)
  {
    id: 22,
    slug: "rose-gold-bracelet",
    name: "Rose Gold Bracelet",
    price: 2400,
    compareAtPrice: null,
    image: "https://images.unsplash.com/photo-1611591437281-460bfbe1220a?w=400&h=400&fit=crop",
    rating: 4.7,
    reviewCount: 65,
    badge: "New",
    category: "jewelry",
    subcategory: "Bracelets",
    inStock: true,
    description: "Elegant rose gold bracelet for daily wear.",
  },
  {
    id: 23,
    slug: "diamond-tennis-bracelet",
    name: "Diamond Tennis Bracelet",
    price: 18000,
    compareAtPrice: 22000,
    image: "https://images.unsplash.com/photo-1611652022419-a9419f74343d?w=400&h=400&fit=crop",
    rating: 5.0,
    reviewCount: 25,
    badge: "Best Seller",
    category: "jewelry",
    subcategory: "Bracelets",
    inStock: true,
    description: "Luxurious diamond tennis bracelet.",
  },
  {
    id: 24,
    slug: "silver-bangle-set",
    name: "Silver Bangle Set",
    price: 3600,
    compareAtPrice: null,
    image: "https://images.unsplash.com/photo-1573408301185-9146fe634ad0?w=400&h=400&fit=crop",
    rating: 4.6,
    reviewCount: 70,
    badge: null,
    category: "jewelry",
    subcategory: "Bracelets",
    inStock: true,
    description: "Set of 3 sterling silver bangles.",
  },

  // ═══════════════════════════════════════
  // SKINCARE (12 products)
  // Face Wash: 3, Moisturizers: 3, Serums: 3, Sunscreen: 3
  // ═══════════════════════════════════════
  // FACE WASH (3)
  {
    id: 25,
    slug: "gentle-face-wash",
    name: "Gentle Face Wash",
    price: 1200,
    compareAtPrice: 1500,
    image: "https://images.unsplash.com/photo-1556228720-195a672e8a03?w=400&h=400&fit=crop",
    rating: 4.7,
    reviewCount: 120,
    badge: "Sale",
    category: "skincare",
    subcategory: "Face Wash",
    inStock: true,
    description: "Gentle daily face wash for all skin types.",
  },
  {
    id: 26,
    slug: "charcoal-face-wash",
    name: "Charcoal Face Wash",
    price: 1400,
    compareAtPrice: 1800,
    image: "https://images.unsplash.com/photo-1608248543803-ba4f8c70ae0b?w=400&h=400&fit=crop",
    rating: 4.8,
    reviewCount: 150,
    badge: "Sale",
    category: "skincare",
    subcategory: "Face Wash",
    inStock: true,
    description: "Charcoal face wash for deep pore cleansing.",
  },
  {
    id: 27,
    slug: "vitamin-c-face-wash",
    name: "Vitamin C Face Wash",
    price: 1600,
    compareAtPrice: null,
    image: "https://images.unsplash.com/photo-1611930022073-b7a4ba5fcccd?w=400&h=400&fit=crop",
    rating: 4.7,
    reviewCount: 100,
    badge: "New",
    category: "skincare",
    subcategory: "Face Wash",
    inStock: true,
    description: "Brightening vitamin C face wash.",
  },

  // MOISTURIZERS (3)
  {
    id: 28,
    slug: "hydrating-moisturizer",
    name: "Hydrating Moisturizer",
    price: 2200,
    compareAtPrice: 2800,
    image: "https://images.unsplash.com/photo-1556228578-8c89e6adf883?w=400&h=400&fit=crop",
    rating: 4.8,
    reviewCount: 140,
    badge: "Sale",
    category: "skincare",
    subcategory: "Moisturizers",
    inStock: true,
    description: "Deep hydrating moisturizer for daily use.",
  },
  {
    id: 29,
    slug: "anti-aging-night-cream",
    name: "Anti-Aging Night Cream",
    price: 2800,
    compareAtPrice: 3500,
    image: "https://images.unsplash.com/photo-1571781926291-c477ebfd024b?w=400&h=400&fit=crop",
    rating: 4.7,
    reviewCount: 85,
    badge: "Sale",
    category: "skincare",
    subcategory: "Moisturizers",
    inStock: true,
    description: "Advanced anti-aging night cream.",
  },
  {
    id: 30,
    slug: "vitamin-e-cream",
    name: "Vitamin E Cream",
    price: 2400,
    compareAtPrice: 2900,
    image: "https://images.unsplash.com/photo-1620916297397-a4a5402a3c6c?w=400&h=400&fit=crop",
    rating: 4.8,
    reviewCount: 95,
    badge: null,
    category: "skincare",
    subcategory: "Moisturizers",
    inStock: true,
    description: "Nourishing vitamin E cream for glowing skin.",
  },

  // SERUMS (3)
  {
    id: 31,
    slug: "vitamin-c-serum",
    name: "Vitamin C Serum",
    price: 1900,
    compareAtPrice: null,
    image: "https://images.unsplash.com/photo-1620916566398-39f1143ab7be?w=400&h=400&fit=crop",
    rating: 4.9,
    reviewCount: 200,
    badge: "Best Seller",
    category: "skincare",
    subcategory: "Serums",
    inStock: true,
    description: "Brightening vitamin C serum for glowing skin.",
  },
  {
    id: 32,
    slug: "retinol-serum",
    name: "Retinol Serum",
    price: 2600,
    compareAtPrice: 3200,
    image: "https://images.unsplash.com/photo-1620916297397-a4a5402a3c6c?w=400&h=400&fit=crop",
    rating: 4.7,
    reviewCount: 75,
    badge: "Sale",
    category: "skincare",
    subcategory: "Serums",
    inStock: true,
    description: "Anti-aging retinol serum.",
  },
  {
    id: 33,
    slug: "hyaluronic-serum",
    name: "Hyaluronic Acid Serum",
    price: 2200,
    compareAtPrice: null,
    image: "https://images.unsplash.com/photo-1612817288484-6f916006741a?w=400&h=400&fit=crop",
    rating: 4.8,
    reviewCount: 130,
    badge: "New",
    category: "skincare",
    subcategory: "Serums",
    inStock: true,
    description: "Hyaluronic acid serum for intense hydration.",
  },

  // SUNSCREEN (3)
  {
    id: 34,
    slug: "spf-50-sunscreen",
    name: "SPF 50 Sunscreen",
    price: 1800,
    compareAtPrice: 2200,
    image: "https://images.unsplash.com/photo-1608248543803-ba4f8c70ae0b?w=400&h=400&fit=crop",
    rating: 4.8,
    reviewCount: 170,
    badge: "Sale",
    category: "skincare",
    subcategory: "Sunscreen",
    inStock: true,
    description: "Broad spectrum SPF 50 sunscreen.",
  },
  {
    id: 35,
    slug: "tinted-sunscreen",
    name: "Tinted Sunscreen",
    price: 2100,
    compareAtPrice: null,
    image: "https://images.unsplash.com/photo-1611930022073-b7a4ba5fcccd?w=400&h=400&fit=crop",
    rating: 4.7,
    reviewCount: 90,
    badge: null,
    category: "skincare",
    subcategory: "Sunscreen",
    inStock: true,
    description: "Tinted sunscreen with light coverage.",
  },
  {
    id: 36,
    slug: "mineral-sunscreen",
    name: "Mineral Sunscreen",
    price: 2400,
    compareAtPrice: 2900,
    image: "https://images.unsplash.com/photo-1556228720-195a672e8a03?w=400&h=400&fit=crop",
    rating: 4.6,
    reviewCount: 65,
    badge: "New",
    category: "skincare",
    subcategory: "Sunscreen",
    inStock: true,
    description: "Mineral-based sunscreen for sensitive skin.",
  },

  // ═══════════════════════════════════════
  // LADIES BAGS (12 products)
  // Handbags: 3, Clutches: 3, Tote Bags: 3, Wallets: 3
  // ═══════════════════════════════════════
  // HANDBAGS (3)
  {
    id: 37,
    slug: "michael-kors-handbag",
    name: "Michael Kors Handbag",
    price: 6500,
    compareAtPrice: 8000,
    image: "https://images.unsplash.com/photo-1584917865442-de89df76afd3?w=400&h=400&fit=crop",
    rating: 4.9,
    reviewCount: 150,
    badge: "Best Seller",
    category: "bags",
    subcategory: "Handbags",
    inStock: true,
    description: "Premium Michael Kors handbag.",
  },
  {
    id: 38,
    slug: "leather-shoulder-bag",
    name: "Leather Shoulder Bag",
    price: 4500,
    compareAtPrice: null,
    image: "https://images.unsplash.com/photo-1548036328-c9fa89d128fa?w=400&h=400&fit=crop",
    rating: 4.7,
    reviewCount: 95,
    badge: null,
    category: "bags",
    subcategory: "Handbags",
    inStock: true,
    description: "Classic leather shoulder bag.",
  },
  {
    id: 39,
    slug: "designer-satchel-bag",
    name: "Designer Satchel Bag",
    price: 5200,
    compareAtPrice: 6500,
    image: "https://images.unsplash.com/photo-1594223274512-ad4803739b7c?w=400&h=400&fit=crop",
    rating: 4.8,
    reviewCount: 70,
    badge: "Sale",
    category: "bags",
    subcategory: "Handbags",
    inStock: true,
    description: "Elegant designer satchel bag.",
  },

  // CLUTCHES (3)
  {
    id: 40,
    slug: "designer-clutch-bag",
    name: "Designer Clutch Bag",
    price: 4500,
    compareAtPrice: null,
    image: "https://images.unsplash.com/photo-1566150905458-1bf1fc113f0d?w=400&h=400&fit=crop",
    rating: 4.6,
    reviewCount: 45,
    badge: null,
    category: "bags",
    subcategory: "Clutches",
    inStock: true,
    description: "Elegant evening clutch for special occasions.",
  },
  {
    id: 41,
    slug: "gold-clutch-bag",
    name: "Gold Clutch Bag",
    price: 3800,
    compareAtPrice: 4800,
    image: "https://images.unsplash.com/photo-1591561954557-26941169b49e?w=400&h=400&fit=crop",
    rating: 4.8,
    reviewCount: 60,
    badge: "Sale",
    category: "bags",
    subcategory: "Clutches",
    inStock: true,
    description: "Shimmering gold clutch for parties.",
  },
  {
    id: 42,
    slug: "velvet-clutch",
    name: "Velvet Clutch",
    price: 3200,
    compareAtPrice: null,
    image: "https://images.unsplash.com/photo-1601924994987-69e26d50dc26?w=400&h=400&fit=crop",
    rating: 4.7,
    reviewCount: 85,
    badge: "New",
    category: "bags",
    subcategory: "Clutches",
    inStock: true,
    description: "Luxurious velvet clutch bag.",
  },

  // TOTE BAGS (3)
  {
    id: 43,
    slug: "luxury-leather-tote-bag",
    name: "Luxury Leather Tote Bag",
    price: 7200,
    compareAtPrice: 9000,
    image: "https://images.unsplash.com/photo-1591561954557-26941169b49e?w=400&h=400&fit=crop",
    rating: 4.8,
    reviewCount: 80,
    badge: "Sale",
    category: "bags",
    subcategory: "Tote Bags",
    inStock: true,
    description: "Spacious leather tote bag.",
  },
  {
    id: 44,
    slug: "canvas-tote-bag",
    name: "Canvas Tote Bag",
    price: 2200,
    compareAtPrice: null,
    image: "https://images.unsplash.com/photo-1544816155-12df9643f363?w=400&h=400&fit=crop",
    rating: 4.5,
    reviewCount: 140,
    badge: null,
    category: "bags",
    subcategory: "Tote Bags",
    inStock: true,
    description: "Casual canvas tote bag for daily use.",
  },
  {
    id: 45,
    slug: "work-tote-bag",
    name: "Professional Work Tote",
    price: 5500,
    compareAtPrice: 6800,
    image: "https://images.unsplash.com/photo-1594223274512-ad4803739b7c?w=400&h=400&fit=crop",
    rating: 4.7,
    reviewCount: 65,
    badge: "Sale",
    category: "bags",
    subcategory: "Tote Bags",
    inStock: true,
    description: "Professional work tote with laptop compartment.",
  },

  // WALLETS (3)
  {
    id: 46,
    slug: "leather-wallet",
    name: "Leather Wallet",
    price: 2800,
    compareAtPrice: 3500,
    image: "https://images.unsplash.com/photo-1627123424574-724758594e93?w=400&h=400&fit=crop",
    rating: 4.7,
    reviewCount: 55,
    badge: "Sale",
    category: "bags",
    subcategory: "Wallets",
    inStock: true,
    description: "Premium leather wallet with card slots.",
  },
  {
    id: 47,
    slug: "zip-around-wallet",
    name: "Zip Around Wallet",
    price: 2400,
    compareAtPrice: null,
    image: "https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=400&h=400&fit=crop",
    rating: 4.6,
    reviewCount: 80,
    badge: null,
    category: "bags",
    subcategory: "Wallets",
    inStock: true,
    description: "Spacious zip around wallet.",
  },
  {
    id: 48,
    slug: "mini-card-holder",
    name: "Mini Card Holder",
    price: 1200,
    compareAtPrice: 1500,
   image: "https://images.unsplash.com/photo-1627123424574-724758594e93?w=400&h=400&fit=crop",
    rating: 4.5,
    reviewCount: 150,
    badge: "New",
    category: "bags",
    subcategory: "Wallets",
    inStock: true,
    description: "Compact card holder for essentials.",
  },
];

// ═══════════════════════════════════════
// 🔍 Helper Functions
// ═══════════════════════════════════════

export const getProductsByCategory = (categorySlug) => {
  return products.filter((p) => p.category === categorySlug);
};

export const getProductBySlug = (slug) => {
  return products.find((p) => p.slug === slug || p.id.toString() === slug);
};

export const getCategoryBySlug = (slug) => {
  return categories.find((c) => c.slug === slug);
};